replicaCount: 2

image:
  repository: 857481120992.dkr.ecr.ap-south-1.amazonaws.com/cloud-devops-platform
  pullPolicy: Always
  tag: "latest"

namespace: devops-platform

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

config:
  nodeEnv: "production"
  port: "8080"
  logLevel: "info"

secrets:
  dbPassword: "SuperSecretPassword123!"
  apiKey: "devops-platform-secret-key"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

probes:
  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5